#!/bin/bash
#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

_git_clone_or_pull "$install_dir/appgenerator"

chown -R "$app:www-data" "$install_dir"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Upgrading app..." --weight=5

pushd "$install_dir" > /dev/null
_update_venv
popd > /dev/null

pushd "$install_dir/appgenerator" > /dev/null
{
    ynh_exec_as_app "$install_dir/venv/bin/pip" install -e . > /dev/null
    ynh_exec_as_app "$install_dir/venv/bin/pip" install gunicorn > /dev/null
    pushd static > /dev/null
    bash ./fetch_assets
    popd > /dev/null
}
popd > /dev/null

ynh_config_add --template="gunicorn.py" --destination="$install_dir/gunicorn.py"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
